//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowtails.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NumbersIn {
            get {
                return ((bool)(this["NumbersIn"]));
            }
            set {
                this["NumbersIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NumbersOut {
            get {
                return ((bool)(this["NumbersOut"]));
            }
            set {
                this["NumbersOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Details {
            get {
                return ((bool)(this["Details"]));
            }
            set {
                this["Details"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Fights {
            get {
                return ((bool)(this["Fights"]));
            }
            set {
                this["Fights"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enemys {
            get {
                return ((bool)(this["Enemys"]));
            }
            set {
                this["Enemys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DPSoutGraph {
            get {
                return ((bool)(this["DPSoutGraph"]));
            }
            set {
                this["DPSoutGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DPSinGraph {
            get {
                return ((bool)(this["DPSinGraph"]));
            }
            set {
                this["DPSinGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HPSoutGraph {
            get {
                return ((bool)(this["HPSoutGraph"]));
            }
            set {
                this["HPSoutGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsWindow {
            get {
                return ((bool)(this["SettingsWindow"]));
            }
            set {
                this["SettingsWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DPSoutSkills {
            get {
                return ((bool)(this["DPSoutSkills"]));
            }
            set {
                this["DPSoutSkills"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaidDPSout {
            get {
                return ((bool)(this["RaidDPSout"]));
            }
            set {
                this["RaidDPSout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaidHPSout {
            get {
                return ((bool)(this["RaidHPSout"]));
            }
            set {
                this["RaidHPSout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string NumbersInSet {
            get {
                return ((string)(this["NumbersInSet"]));
            }
            set {
                this["NumbersInSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string NumbersOutSet {
            get {
                return ((string)(this["NumbersOutSet"]));
            }
            set {
                this["NumbersOutSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string DetailsSet {
            get {
                return ((string)(this["DetailsSet"]));
            }
            set {
                this["DetailsSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string FightsSet {
            get {
                return ((string)(this["FightsSet"]));
            }
            set {
                this["FightsSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string EnemysSet {
            get {
                return ((string)(this["EnemysSet"]));
            }
            set {
                this["EnemysSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string DPSoutGraphSet {
            get {
                return ((string)(this["DPSoutGraphSet"]));
            }
            set {
                this["DPSoutGraphSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string DPSinGraphSet {
            get {
                return ((string)(this["DPSinGraphSet"]));
            }
            set {
                this["DPSinGraphSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string HPSoutGraphSet {
            get {
                return ((string)(this["HPSoutGraphSet"]));
            }
            set {
                this["HPSoutGraphSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string SettingsWindowSet {
            get {
                return ((string)(this["SettingsWindowSet"]));
            }
            set {
                this["SettingsWindowSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string DPSoutSkillsSet {
            get {
                return ((string)(this["DPSoutSkillsSet"]));
            }
            set {
                this["DPSoutSkillsSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string RaidDPSoutSet {
            get {
                return ((string)(this["RaidDPSoutSet"]));
            }
            set {
                this["RaidDPSoutSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string RaidHPSoutSet {
            get {
                return ((string)(this["RaidHPSoutSet"]));
            }
            set {
                this["RaidHPSoutSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Opacity_ {
            get {
                return ((int)(this["Opacity_"]));
            }
            set {
                this["Opacity_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FightDura_ {
            get {
                return ((int)(this["FightDura_"]));
            }
            set {
                this["FightDura_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApiKey_ {
            get {
                return ((int)(this["ApiKey_"]));
            }
            set {
                this["ApiKey_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FightButton_ {
            get {
                return ((bool)(this["FightButton_"]));
            }
            set {
                this["FightButton_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Lock_ {
            get {
                return ((bool)(this["Lock_"]));
            }
            set {
                this["Lock_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Account_ {
            get {
                return ((string)(this["Account_"]));
            }
            set {
                this["Account_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Online_ {
            get {
                return ((bool)(this["Online_"]));
            }
            set {
                this["Online_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOnlyInFight {
            get {
                return ((bool)(this["ShowOnlyInFight"]));
            }
            set {
                this["ShowOnlyInFight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string ChanPWD {
            get {
                return ((string)(this["ChanPWD"]));
            }
            set {
                this["ChanPWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DockWindow {
            get {
                return ((bool)(this["DockWindow"]));
            }
            set {
                this["DockWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverlayDis_ {
            get {
                return ((bool)(this["OverlayDis_"]));
            }
            set {
                this["OverlayDis_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartCrowfall {
            get {
                return ((bool)(this["StartCrowfall"]));
            }
            set {
                this["StartCrowfall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CrowfallFolder {
            get {
                return ((string)(this["CrowfallFolder"]));
            }
            set {
                this["CrowfallFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NetworkOptions {
            get {
                return ((bool)(this["NetworkOptions"]));
            }
            set {
                this["NetworkOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tut {
            get {
                return ((bool)(this["tut"]));
            }
            set {
                this["tut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Class_ {
            get {
                return ((int)(this["Class_"]));
            }
            set {
                this["Class_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DPSInOutType {
            get {
                return ((bool)(this["DPSInOutType"]));
            }
            set {
                this["DPSInOutType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string DPSInOutTypeSet {
            get {
                return ((string)(this["DPSInOutTypeSet"]));
            }
            set {
                this["DPSInOutTypeSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExtendedNetwork {
            get {
                return ((bool)(this["ExtendedNetwork"]));
            }
            set {
                this["ExtendedNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string playerraidtoolSet {
            get {
                return ((string)(this["playerraidtoolSet"]));
            }
            set {
                this["playerraidtoolSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string SettingsButtonSet {
            get {
                return ((string)(this["SettingsButtonSet"]));
            }
            set {
                this["SettingsButtonSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int uilang {
            get {
                return ((int)(this["uilang"]));
            }
            set {
                this["uilang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int gameLang {
            get {
                return ((int)(this["gameLang"]));
            }
            set {
                this["gameLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArchivRaid {
            get {
                return ((bool)(this["ArchivRaid"]));
            }
            set {
                this["ArchivRaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string ArchivRaidSet {
            get {
                return ((string)(this["ArchivRaidSet"]));
            }
            set {
                this["ArchivRaidSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;0;0;0;")]
        public string SettingsButtonSetArchiv {
            get {
                return ((string)(this["SettingsButtonSetArchiv"]));
            }
            set {
                this["SettingsButtonSetArchiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerUrl {
            get {
                return ((string)(this["ServerUrl"]));
            }
            set {
                this["ServerUrl"] = value;
            }
        }
    }
}
